project_id = "mvcahkhlgbggcbvutjfm"

[functions.send-report-confirmation]
verify_jwt = true

[functions.send-email-update]
verify_jwt = true

[functions.process-face-recognition]
verify_jwt = true

[functions.receive-sms-sighting]
verify_jwt = false
