project_id = "mvcahkhlgbggcbvutjfm"

[functions.send-report-confirmation]
verify_jwt = true

[functions.send-email-update]
verify_jwt = true

[functions.process-face-recognition]
verify_jwt = true

[functions.receive-sms-sighting]
verify_jwt = false

[functions.send-message-sms]
verify_jwt = true

[functions.send-message-notification]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.search-by-image]
verify_jwt = false
